# Generated by Django 3.2.14 on 2022-08-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(related_name='users_favorite', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(related_name='users_shopping_cart', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
