# Generated by Django 3.2.14 on 2022-08-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220808_0326'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_to_name',
        ),
    ]
