# Generated by Django 3.2.14 on 2022-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_unique_author_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
