# Generated by Django 3.2.14 on 2022-08-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Количество'),
        ),
    ]
